language: shell
services:
  - docker
before_install:
  - sudo pip uninstall --yes pyopenssl && sudo pip install -U pyopenssl # fix for molecule
  - ./tads install-dependencies --no-password --force --dev
install:
  - ./tads terraform production init
jobs:
  include:
    - stage: test
      name: Lint
      script: make lint
    - stage: test
      name: Test scripts
      script: make test-scripts
    - stage: test
      name: Test Ansible roles
      script: make test-ansible-roles
    - stage: test
      name: Ansible End-to-End test
      script: make test-ansible-e2e
