---
###
# local environments variables
##
# This group applies to local environments (localhost and vagrant)
#
# You may override some variables from all.yml here...
##

# We can't use ACME in local environments
# Traefik's self signed certificate will be used
letsencrypt: False

# Credentials
# You should set default development credentials here
credentials:
  example_app:
    username: dev
    password: 123456789
